// Ejemplo mínimo funcional, copiado literalmente de
// cotizador-alva-v3/.agents/skills/arquitecto-wbs/SKILL.md (Parte 5),
// para demostrar que este motor consume el mismo formato de archivo
// "LaOfi S.A.S." que exporta/importa la app original.
export const sampleProjectWireJson = {
  empresa: 'LaOfi S.A.S.',
  version: '14.2',
  timestamp: '2026-09-01T12:00:00.000Z',
  data: {
    version: '14.8',
    categorias: {
      'n1-1': { id: 'n1-1', name: '1. COSTOS DIRECTOS' },
      'n1-2': { id: 'n1-2', name: '2. COSTOS INDIRECTOS' },
      'n1-3': { id: 'n1-3', name: '3. GASTOS GENERALES' },
      'n1-4': { id: 'n1-4', name: '4. UTILIDAD' },
    },
    rubros_principales: {
      'n2-1': { id: 'n2-1', parentId: 'n1-1', name: '1. Remuneraciones' },
      'n2-10': { id: 'n2-10', parentId: 'n1-2', name: '1. Personal de dirección' },
    },
    rubros_secundarios: {
      'sec-001': { id: 'sec-001', parentId: 'n2-10', name: 'Honorarios Factura' },
      'sec-002': { id: 'sec-002', parentId: 'n2-1', name: 'Rol de Pagos' },
    },
    rubros_detallados: {
      'det-001': {
        id: 'det-001',
        parentId: 'sec-001',
        name: 'Director de Proyecto PMP',
        description: 'Gestión integral del proyecto.',
      },
      'det-002': {
        id: 'det-002',
        parentId: 'sec-002',
        name: 'Especialista SIG',
        description: 'Análisis espacial y geodatabase.',
      },
    },
    tarifas: {
      'tar-001': {
        id: 'tar-001',
        parentId: 'det-001',
        supplier: 'Servicios Profesionales',
        unitCost: 2178.57,
        unit: 'Mes',
      },
      'tar-002': {
        id: 'tar-002',
        parentId: 'det-002',
        supplier: 'Nómina ALVA',
        unitCost: 1500,
        unit: 'Mes',
      },
    },
    elementos_wbs: {
      'wbs-001': {
        id: 'wbs-001',
        code: '1',
        name: 'FASE 1: DIAGNÓSTICO INICIAL',
        levelType: 'Fase',
        parentId: null,
        desc_general: 'Diagnóstico del estado actual del sistema.',
        desc_smart: 'Completar diagnóstico en 30 días.',
        desc_kpi: '100% variables diagnosticadas.',
        desc_aporte: 'Línea base para la planificación.',
        desc_insumos: 'Información institucional existente.',
        desc_tecnica: 'Metodología de auditoría institucional.',
        deliverable: 'Informe de Diagnóstico',
        startDay: 1,
        duration: 30,
        isActive: true,
      },
      'wbs-002': {
        id: 'wbs-002',
        code: '1.1',
        name: 'Recopilación de Información',
        levelType: 'Actividad',
        parentId: 'wbs-001',
        desc_general: 'Recoger documentación existente.',
        desc_smart: '',
        desc_kpi: '',
        desc_aporte: '',
        desc_insumos: '',
        desc_tecnica: '',
        deliverable: '',
        startDay: 1,
        duration: 15,
        isActive: true,
      },
      'wbs-003': {
        id: 'wbs-003',
        code: '1.1.1',
        name: 'Revisión Documental',
        levelType: 'Acción',
        parentId: 'wbs-002',
        desc_general: 'Análisis de documentos normativos y técnicos.',
        desc_smart: '',
        desc_kpi: '',
        desc_aporte: '',
        desc_insumos: '',
        desc_tecnica: '',
        deliverable: 'Matriz de documentos',
        startDay: 1,
        duration: 15,
        isActive: true,
      },
      'wbs-004': {
        id: 'wbs-004',
        code: '1.1.1.01',
        name: 'Levantamiento de información catastral existente.',
        levelType: 'Tarea',
        parentId: 'wbs-003',
        desc_general: 'Revisión de bases de datos, cartografía y registros existentes.',
        desc_smart: 'Duración: 10 días.',
        desc_kpi: '',
        desc_aporte: '',
        desc_insumos: 'Bases de datos municipales, cartografía histórica.',
        desc_tecnica: 'Análisis SIG de capas catastrales existentes.',
        deliverable: 'Inventario de información',
        startDay: 1,
        duration: 10,
        isActive: true,
      },
    },
    recursos_wbs: {
      'res-001': {
        id: 'res-001',
        elemento_wbs_id: 'wbs-001',
        tarifa_id: 'tar-001',
        quantity: 1,
        quantityUnit: 'Persona',
        time: 1,
        timeUnit: 'Mes',
      },
      'res-002': {
        id: 'res-002',
        elemento_wbs_id: 'wbs-004',
        tarifa_id: 'tar-002',
        quantity: 1,
        quantityUnit: 'Persona',
        time: 0.5,
        timeUnit: 'Mes',
      },
    },
    oferta_comercial: {
      version: '14.8',
      clientName: 'GAD Municipal Ejemplo',
      projectName: 'Diagnóstico Catastral',
      projectNameFull: 'Diagnóstico integral del sistema catastral municipal.',
      sbu: 482,
      date: '',
      quoteType: 'economic',
      maxDetailLevel: 4,
      introText: 'Propuesta técnica y económica bajo estructura jerárquica ALVA v1.5.',
      discountType: 'none',
      discountValue: 0,
      quoteSequence: 'COT-EJEMPLO-2026',
      targetBudget: 0,
      globalInsurance: 0,
      globalContingency: 0,
      globalProfit: 35,
      milestones: [
        { id: 'm1', name: 'Anticipo y Preparación Operativa', percentage: 30, linkedWbsId: '' },
        { id: 'm2', name: 'Entregables Finales y Liquidación', percentage: 70, linkedWbsId: '' },
      ],
    },
  },
};
